//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGen.NTier.Kick.PresentationLayer.WebLayer {
    
    
    public partial class LOG_Log {
        
        /// <summary>
        /// DDL_Logtype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickListBox DDL_Logtype;
        
        /// <summary>
        /// DDL_Errortype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickListBox DDL_Errortype;
        
        /// <summary>
        /// CBX_Read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CBX_Read;
        
        /// <summary>
        /// TXT_Date_begin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.NTier.Kick.PresentationLayer.WebLayer.htmlDatePicker TXT_Date_begin;
        
        /// <summary>
        /// TXT_Date_end control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.NTier.Kick.PresentationLayer.WebLayer.htmlDatePicker TXT_Date_end;
        
        /// <summary>
        /// LBL_Date_lastDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.LinkButton LBL_Date_lastDay;
        
        /// <summary>
        /// LBL_Date_lastWeek control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.LinkButton LBL_Date_lastWeek;
        
        /// <summary>
        /// LBL_Date_clear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.LinkButton LBL_Date_clear;
        
        /// <summary>
        /// BTN_Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.Button BTN_Search;
        
        /// <summary>
        /// REP_Log control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Anthem.Repeater REP_Log;
    }
}
