//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGen.NTier.Kick.PresentationLayer.WebLayer {
    
    
    public partial class NWS_News_list {
        
        /// <summary>
        /// TXT_Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_Text;
        
        /// <summary>
        /// DDL_Approved control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickListBox DDL_Approved;
        
        /// <summary>
        /// TXT_Begin_date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.NTier.Kick.PresentationLayer.WebLayer.htmlDatePicker TXT_Begin_date;
        
        /// <summary>
        /// TXT_End_date control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.NTier.Kick.PresentationLayer.WebLayer.htmlDatePicker TXT_End_date;
        
        /// <summary>
        /// CBL_Tags control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickCheckBoxList CBL_Tags;
        
        /// <summary>
        /// CBL_Author control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickCheckBoxList CBL_Author;
        
        /// <summary>
        /// CBL_Source control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickCheckBoxList CBL_Source;
        
        /// <summary>
        /// CBL_Highlight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickCheckBoxList CBL_Highlight;
        
        /// <summary>
        /// CBL_Profile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OGen.Libraries.PresentationLayer.WebForms.KickCheckBoxList CBL_Profile;
        
        /// <summary>
        /// BTN_Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BTN_Search;
        
        /// <summary>
        /// REP_SearchResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater REP_SearchResults;
    }
}
