ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFUser_fkey" FOREIGN KEY (
		"IFUser"
	) REFERENCES "CRD_User" (
		"IDUser"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFUser_fkey"
GO

ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFUser__read_fkey" FOREIGN KEY (
		"IFUser__read"
	) REFERENCES "CRD_User" (
		"IDUser"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFUser__read_fkey"
GO

ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFPermission_fkey" FOREIGN KEY (
		"IFPermission"
	) REFERENCES "CRD_Permission" (
		"IDPermission"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFPermission_fkey"
GO

ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFApplication_fkey" FOREIGN KEY (
		"IFApplication"
	) REFERENCES "APP_Application" (
		"IDApplication"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFApplication_fkey"
GO

ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFType_fkey" FOREIGN KEY (
		"IFType"
	) REFERENCES "LOG_Type" (
		"IDType"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFType_fkey"
GO

ALTER TABLE "LOG_Log" WITH CHECK 
	ADD CONSTRAINT "LOG_Log_IFError_fkey" FOREIGN KEY (
		"IFError"
	) REFERENCES "LOG_Error" (
		"IDError"
	)
GO
ALTER TABLE "LOG_Log" CHECK CONSTRAINT "LOG_Log_IFError_fkey"
GO

