ALTER TABLE "NWS_UserTag" WITH CHECK 
	ADD CONSTRAINT "NWS_UserTag_IFUser_fkey" FOREIGN KEY (
		"IFUser"
	) REFERENCES "NET_User" (
		"IFUser"
	)
GO
ALTER TABLE "NWS_UserTag" CHECK CONSTRAINT "NWS_UserTag_IFUser_fkey"
GO

ALTER TABLE "NWS_UserTag" WITH CHECK 
	ADD CONSTRAINT "NWS_UserTag_IFTag_fkey" FOREIGN KEY (
		"IFTag"
	) REFERENCES "NWS_Tag" (
		"IDTag"
	)
GO
ALTER TABLE "NWS_UserTag" CHECK CONSTRAINT "NWS_UserTag_IFTag_fkey"
GO

