ALTER TABLE "LOG_Log"
  ADD CONSTRAINT "LOG_Log_IFUser_fkey" FOREIGN KEY ("IFUser")
    REFERENCES "CRD_User" ("IDUser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "LOG_Log_IFUser__read_fkey" FOREIGN KEY ("IFUser__read")
    REFERENCES "CRD_User" ("IDUser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "LOG_Log_IFPermission_fkey" FOREIGN KEY ("IFPermission")
    REFERENCES "CRD_Permission" ("IDPermission") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "LOG_Log_IFApplication_fkey" FOREIGN KEY ("IFApplication")
    REFERENCES "APP_Application" ("IDApplication") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "LOG_Log_IFType_fkey" FOREIGN KEY ("IFType")
    REFERENCES "LOG_Type" ("IDType") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "LOG_Log_IFError_fkey" FOREIGN KEY ("IFError")
    REFERENCES "LOG_Error" ("IDError") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
;

