ALTER TABLE "FRM_GroupAnswer"
  ADD CONSTRAINT "FRM_GroupAnswer_IFGroup_fkey" FOREIGN KEY ("IFGroup")
    REFERENCES "FRM_Group" ("IDGroup") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "FRM_GroupAnswer_IFAnswer_fkey" FOREIGN KEY ("IFAnswer")
    REFERENCES "FRM_Answer" ("IDAnswer") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "FRM_GroupAnswer_IFUser__audit_fkey" FOREIGN KEY ("IFUser__audit")
    REFERENCES "CRD_User" ("IDUser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
;

