ALTER TABLE "NET_BrowserUser"
  ADD CONSTRAINT "NET_BrowserUser_IFBrowser_fkey" FOREIGN KEY ("IFBrowser")
    REFERENCES "NET_Browser" ("IDBrowser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "NET_BrowserUser_IFUser_fkey" FOREIGN KEY ("IFUser")
    REFERENCES "NET_User" ("IFUser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
;

