ALTER TABLE "CRD_UserProfile"
  ADD CONSTRAINT "CRD_UserProfile_IFUser_fkey" FOREIGN KEY ("IFUser")
    REFERENCES "CRD_User" ("IDUser") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "CRD_UserProfile_IFProfile_fkey" FOREIGN KEY ("IFProfile")
    REFERENCES "CRD_Profile" ("IDProfile") MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
;

